Robot Accountant func was created
mate-academy/js_sum-with-closure pull request #1162
Opened 2022-07-16 15:33 UTC by yuliia-dronova

2022-07-17 13:53 UTC, oleksandr-kotliarov requested changes

2022-07-17 13:53 UTC, oleksandr-kotliarov commented on src/makeRobotAccountant.js
> +      return arg1 + arg2;
```suggestion
      return callCount > 3 && callCount % 2 === 0
        ? 'Bzzz... Error!'
        : arg1 + arg2;
```

2022-07-17 13:54 UTC, yuliia-dronova commented on src/makeRobotAccountant.js
> +      return arg1 + arg2;
Точно, дякую :)

2022-07-18 06:35 UTC, VETALEK approved these changes
🔥

2023-08-01 13:48 UTC, closed without merging