add sum function
mate-academy/js_sum-with-closure pull request #260
Opened 2020-09-21 16:09 UTC by akulahere

2020-09-21 17:32 UTC, vkryvytskyy requested changes

2020-09-21 17:32 UTC, vkryvytskyy commented on src/makeRobotAccountant.js
> +  return sum;
возвращай функцию сразу в 11 строке

2020-09-21 17:32 UTC, vkryvytskyy commented on src/makeRobotAccountant.js
> +    };
тут хватит одной конструкции if..else

2020-09-21 17:32 UTC, vkryvytskyy commented on src/makeRobotAccountant.js
> +        return 'Bzzz... Error!';
можно написать проверку таким образом, чтобы `return 'Bzzz... Error!'` встречалось в коде только раз

2020-09-21 17:32 UTC, vkryvytskyy commented on src/makeRobotAccountant.js
> +  function sum(num1) {
используй стрелочные функции

2020-09-21 18:42 UTC, akulahere commented on src/makeRobotAccountant.js
> +  return sum;
fixed

2020-09-21 18:42 UTC, akulahere commented on src/makeRobotAccountant.js
> +    };
fixed

2020-09-21 18:42 UTC, akulahere commented on src/makeRobotAccountant.js
> +        return 'Bzzz... Error!';
fixed

2020-09-21 18:43 UTC, akulahere commented on src/makeRobotAccountant.js
> +  function sum(num1) {
fixed

2020-09-22 17:34 UTC, vkryvytskyy approved these changes

2022-06-22 14:30 UTC, closed without merging