solved
mate-academy/js_sum-with-closure pull request #950
Opened 2022-04-13 14:35 UTC by misha200119

2022-04-14 14:04 UTC, plankton9991 approved these changes
good job)

2022-04-14 22:29 UTC, AlinaMatuschak requested changes

2022-04-14 22:29 UTC, AlinaMatuschak commented on src/makeRobotAccountant.js
> +          ? value0 + value1 : 'Bzzz... Error!';
Avoid nested ternary

2022-04-15 06:18 UTC, AlinaMatuschak approved these changes

2022-04-15 06:18 UTC, AlinaMatuschak commented on src/makeRobotAccountant.js
> +    return function(value1) {
```suggestion
  return (value0) => (value1) => {
```

2025-02-20 16:02 UTC, closed without merging