Looks like i did it
mate-academy/js_sum-with-closure pull request #982
Opened 2022-05-03 09:19 UTC by Havrysh

2022-05-04 12:16 UTC, aliceblunt8 requested changes

2022-05-04 12:16 UTC, aliceblunt8 commented on src/makeRobotAccountant.js
> +      }
combine cases when you return x + y

2022-05-04 12:29 UTC, Havrysh commented on src/makeRobotAccountant.js
> +      }
yes, ma'am

2022-05-05 11:47 UTC, Bohdan-Maksymiuk approved these changes
Good job 👍

2024-12-11 13:38 UTC, closed without merging